MyohanMeeting/MeMyo-Backend

- MyohanMeeting/src/main/java/meet/myo/domain/authority/Authority.java
- MyohanMeeting/src/main/java/meet/myo/domain/authority/MemberAuthority.java
- MyohanMeeting/src/main/java/meet/myo/domain/cat/Cat.java
- MyohanMeeting/src/main/java/meet/myo/domain/cat/CatPictures.java
#1 
해당 이슈 관련 풀리퀘스트입니다.
작업하면서 필요해보이는 부분 수정했습니다~! 상세 내용은 커밋 메시지에 있습니다.
> Feat/ authority 엔티티 생성 외 2건

- MyohanMeeting/src/main/java/meet/myo/domain/BaseAuditingListener.java
- MyohanMeeting/src/main/java/meet/myo/domain/Member.java
- MyohanMeeting/src/main/java/meet/myo/domain/Upload.java
- MyohanMeeting/src/main/java/meet/myo/domain/adopt/AdoptApplication.java
- MyohanMeeting/src/main/java/meet/myo/domain/adopt/AdoptNotice.java
- MyohanMeeting/src/main/java/meet/myo/domain/authority/Authority.java
- MyohanMeeting/src/main/java/meet/myo/domain/authority/MemberAuthority.java
- MyohanMeeting/src/main/java/meet/myo/domain/cat/Cat.java
- MyohanMeeting/src/main/java/meet/myo/domain/cat/CatPictures.java
- #8 
생성시간, 수정시간, 삭제시간 관리할 수 있는 auditing listener를 추가하고 각 엔티티에서 상속
> feat: auditing listener 추가

- MyohanMeeting/src/main/java/meet/myo/repository/AuthorityRepository.java
우선 Spring Data JPA 기본 레포지토리만 생성
추후 Querydsl 필요 시 추가작업 요망
> feat: authority 관련 레포지토리 추가

- MyohanMeeting/src/main/java/meet/myo/domain/Certified.java
- MyohanMeeting/src/main/java/meet/myo/domain/EmailCertification.java
- MyohanMeeting/src/main/java/meet/myo/domain/Member.java
이메일 인증에 사용될 UUID, 만료시간 등을 관리하는 엔티티 생성
회원 엔티티에 이메일 인증 여부 및 인증여부 업데이트 메서드 추가
> feat: 이메일 인증 관련 엔티티 작업

- MyohanMeeting/src/main/java/meet/myo/dto/request/AdoptApplicationCreateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/AdoptApplicationUpdateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/AdoptNoticeCreateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/AdoptNoticeUpdateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/CertifyEmailRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/EmailUpdateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/MemberDirectCreateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/MemberOauthCreateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/MemberUpdateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/OauthUpdateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/PasswordUpdateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/AdoptApplicationResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/AdoptNoticeResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/EmailUpdateResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/MemberAuthorityResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/MemberResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/MemberUpdateResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/OauthUpdateResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/PasswordUpdateResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/UploadResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/repository/MemberAuthorityRepository.java
- MyohanMeeting/src/main/java/meet/myo/search/AdoptApplicationSearch.java
- MyohanMeeting/src/main/java/meet/myo/search/AdoptNoticeSearch.java
- MyohanMeeting/src/main/java/meet/myo/service/AdoptApplicationService.java
- MyohanMeeting/src/main/java/meet/myo/service/AdoptNoticeService.java
- MyohanMeeting/src/main/java/meet/myo/service/MemberAuthorityService.java
- MyohanMeeting/src/main/java/meet/myo/service/MemberService.java
- MyohanMeeting/src/main/java/meet/myo/service/UploadService.java
서비스레이어 메소드 시그니처 생성
및 사용되는 dto, search 클래스 생성
> feat: 서비스레이어 생성

- MyohanMeeting/.gitignore
- MyohanMeeting/src/main/java/meet/myo/config/ApplicationConfig.java
- MyohanMeeting/src/main/java/meet/myo/domain/Member.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/adopt/AdoptNoticeResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/repository/EmailCertificationRepository.java
- MyohanMeeting/src/main/java/meet/myo/service/CustomUserDetailsService.java
- MyohanMeeting/src/main/java/meet/myo/service/MemberService.java
- MyohanMeeting/src/main/resources/application.yml
- 시크릿 키 설정파일 분리하고 .gitignore에 추가
- ApplicationConfig 생성하고 Auditing 활성화
- 빠진 임포트 추가
- 메서드명 수정
> fix: 각자 작업분량 머지 후 발생한 자잘한 오류 수정

- MyohanMeeting/src/main/java/meet/myo/domain/Favorite.java
- MyohanMeeting/src/main/java/meet/myo/domain/Upload.java
- MyohanMeeting/src/main/java/meet/myo/domain/adopt/application/AdoptApplication.java
- MyohanMeeting/src/main/java/meet/myo/domain/adopt/notice/AdoptNotice.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/CreateFavoriteRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/adopt/AdoptApplicationCreateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/adopt/AdoptApplicationUpdateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/FavoriteResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/UploadResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/exception/NotFoundException.java
- MyohanMeeting/src/main/java/meet/myo/exception/RestExceptionHandler.java
- MyohanMeeting/src/main/java/meet/myo/repository/AdoptApplicationRepository.java
- MyohanMeeting/src/main/java/meet/myo/repository/AdoptNoticeCommentRepository.java
- MyohanMeeting/src/main/java/meet/myo/repository/AdoptNoticeRepository.java
- MyohanMeeting/src/main/java/meet/myo/repository/CatRepository.java
- MyohanMeeting/src/main/java/meet/myo/repository/FavoriteRepository.java
- MyohanMeeting/src/main/java/meet/myo/repository/UploadRepository.java
- MyohanMeeting/src/main/java/meet/myo/service/AdoptApplicationService.java
- MyohanMeeting/src/main/java/meet/myo/service/AdoptNoticeService.java
- MyohanMeeting/src/main/java/meet/myo/service/FavoriteService.java
- MyohanMeeting/src/main/java/meet/myo/service/MemberService.java
- MyohanMeeting/src/main/java/meet/myo/service/UploadService.java
파일업로드
찜하기
입양공고올리기
입양신청하기
서비스레이어
초안입니다
> Feat/ Upload , Favorite , Adopt , Application

- MyohanMeeting/src/main/java/meet/myo/config/SecurityConfig.java
- MyohanMeeting/src/main/java/meet/myo/jwt/JwtAccessDeniedHandler.java
- MyohanMeeting/src/main/java/meet/myo/jwt/JwtAuthenticationEntryPoint.java
- swagger 리소스에 접근권한이 허용되어있지 않아 문서가 제대로 표시되지 않던 상황 수정
> fix: swagger 접근권한 추가

- MyohanMeeting/build.gradle
- MyohanMeeting/src/main/java/meet/myo/config/MailConfig.java
- MyohanMeeting/src/main/java/meet/myo/domain/EmailCertification.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/member/CertifyEmailRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/repository/EmailCertificationRepository.java
- MyohanMeeting/src/main/java/meet/myo/service/EmailService.java
- MyohanMeeting/src/main/java/meet/myo/service/MemberService.java
1. 회원에게 이메일발송, UUID 값 전송
2. UUID값 회원이 검증 시 Certified
> Feat/메일발송, 인증

- MyohanMeeting/src/main/java/meet/myo/domain/Member.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/member/MemberDirectCreateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/member/MemberOauthCreateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/adopt/AdoptApplicationResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/adopt/AdoptNoticeCommentResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/adopt/AdoptNoticeResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/adopt/AdoptNoticeSummaryResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/member/MemberResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/service/MemberService.java
- MyohanMeeting/src/main/resources/import.sql
- 테스트용 데이터 추가
- 회원가입 시 기본 프로필 이미지 등록하도록 수정
- 가입 시에는 프로필 이미지 받지 않음
- createdAt 타입 LocalDateTime->String으로 수정
- AdoptNoticeResponseDto에 title 누락 수정
> Fix/ #54 issue 및 직렬화 관련 오류 수정

- MyohanMeeting/build.gradle
- MyohanMeeting/src/main/java/meet/myo/config/JsonNullableConfig.java
- MyohanMeeting/src/main/java/meet/myo/controller/AdoptApplicationController.java
- MyohanMeeting/src/main/java/meet/myo/controller/AdoptNoticeCommentController.java
- MyohanMeeting/src/main/java/meet/myo/controller/AdoptNoticeController.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/adopt/AdoptApplicationCreateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/adopt/AdoptApplicationUpdateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/adopt/AdoptNoticeCreateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/adopt/AdoptNoticeUpdateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/request/member/MemberUpdateRequestDto.java
- MyohanMeeting/src/main/java/meet/myo/repository/CatPictureRepository.java
- MyohanMeeting/src/main/java/meet/myo/service/AdoptApplicationService.java
- MyohanMeeting/src/main/java/meet/myo/service/AdoptNoticeService.java
- MyohanMeeting/src/main/java/meet/myo/service/MemberService.java
- JsonNullable 의존성 추가 및 설정파일 작성
- 작성/수정 dto 분리
- 일부 불필요한 patch 메서드 put으로 수정
- 서비스 레이어에 patch 메서드 동작 구현
- CatPictureRepository 클래스 추가
> Feat/ http patch 메서드 구현

- .gitignore
- MyohanMeeting/build.gradle
- MyohanMeeting/src/main/resources/application-dev.yml
- dev 환경 mysql 연결하도록 설정 추가
- gitignore 수정
> feat/ mysql 마이그레이션 설정 추가

- MyohanMeeting/src/main/java/meet/myo/controller/AuthController.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/SigninResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/dto/response/member/MemberUpdateResponseDto.java
- MyohanMeeting/src/main/java/meet/myo/service/AuthService.java
- #42
- 로그인 시 이메일, 닉네임, 프로필 이미지 포함해 응답하도록 응답 수정
- 일부 인증 관련 예외 클래스 변경(JwtException->AccessDeniedException)
- 프로필 이미지 url 프로퍼티명 통일
> fix/ 로그인 response 수정

- MyohanMeeting/src/main/java/meet/myo/exception/ExceptionHandlerFilter.java
- MyohanMeeting/src/main/java/meet/myo/exception/RestExceptionHandler.java
- MyohanMeeting/src/main/java/meet/myo/jwt/JwtFilter.java
- MyohanMeeting/src/main/java/meet/myo/jwt/JwtSecurityConfig.java
- #65 
- ExceptionHandlerFilter 추가
- 임시로 JwtFilter에서 처리하던 403 예외 삭제
- RestExceptionHandler에 MissingParam 예외 추가
- RuntimeException 처리하지 않도록 수정
> feat: filter단 예외처리기 추가

- MyohanMeeting/src/main/java/meet/myo/controller/MemberController.java
- MyohanMeeting/src/main/java/meet/myo/service/MemberService.java
- MyohanMeeting/src/main/java/meet/myo/service/SignInService.java
- #75
- 가입 과정은 SignInService, 가입 이후의 기능은 MemberService에 작성
> fix/ MemberService 분리

- .github/build-and-deploy.yml
- .github/build-test.yml
- 메인 브랜치에 PR 시 빌드 테스트만 진행
- 메인 브랜치에 push 시 배포까지 진행
> fix/ Github Actions 스크립트 수정

- MyohanMeeting/src/main/java/meet/myo/config/SecurityConfig.java
- MyohanMeeting/src/main/java/meet/myo/config/WebConfig.java
- MyohanMeeting/src/main/java/meet/myo/service/EmailService.java
- MyohanMeeting/src/main/resources/application-dev.yml
- MyohanMeeting/src/main/resources/application-local.yml
- MyohanMeeting/src/main/resources/application.yml
**feat: cors 설정**
- 환경변수로 설정된 client url에 대한 cors 허용
**fix: client 환경설정 변경**
- client-env.yml 삭제, 배포환경에 따라 url 선택되도록 수정
- 배포환경에 따라 다른 secret 파일 import하도록 수정
> feat: cors 설정

- .github/workflows/build-and-deploy.yml
- .github/workflows/build-test.yml
> fix: github action workflows 수정

- MyohanMeeting/build.gradle
- MyohanMeeting/src/main/java/meet/myo/config/RedisConfig.java
- MyohanMeeting/src/main/java/meet/myo/config/SecurityConfig.java
- MyohanMeeting/src/main/java/meet/myo/exception/ExceptionHandlerFilter.java
- MyohanMeeting/src/main/java/meet/myo/jwt/JwtFilter.java
- MyohanMeeting/src/main/java/meet/myo/jwt/JwtSecurityConfig.java
- MyohanMeeting/src/main/java/meet/myo/jwt/TokenProvider.java
- MyohanMeeting/src/main/java/meet/myo/service/AuthService.java
- Redis 의존성 추가, config 파일 작성
- 로그아웃 엔드포인트 호출하면 블랙리스트 토큰으로 등록하고 리프레시 토큰 삭제
- 이후 JwtFilter에서 토큰 블랙리스트 검증
- ExceptionHandlerFilter import 오류 수정
> feat: 로그아웃 구현

- MyohanMeeting/src/main/java/meet/myo/config/WebConfig.java
- MyohanMeeting/src/main/java/meet/myo/service/EmailService.java
- 서버 url도 환경변수로 추가함에 따라 기존 환경변수 수정
- 서버 url: ${deploy.server.url}
- 클라이언트 url: ${deploy.client.url}
> fix: 배포 url 환경변수 수정

- .github/workflows/build-and-deploy.yml
- MyohanMeeting/src/main/java/meet/myo/config/SpringDocsConfig.java
- MyohanMeeting/src/main/resources/application-dev.yml
- springdoc에 server url 추가
- mysql db로 변경
- github actions workflow 변경
> fix: 배포환경 변경

- .github/workflows/build-and-deploy.yml
> fix: 환경변수명 오류 수정

- MyohanMeeting/src/main/java/meet/myo/config/WebConfig.java
- MyohanMeeting/src/main/resources/application.yml
- allowedOrigins() 변수 전달 오류 수정
> fix: webconfig 수정

- MyohanMeeting/src/main/java/meet/myo/config/WebConfig.java
- allowed methods *로 수정
- allowCredential, maxAge 추가
> fix: cors 설정 수정

- MyohanMeeting/src/main/resources/dev-db-h2.yml
> hotfix: h2 마이그레이션 오류 수정

- MyohanMeeting/src/main/java/meet/myo/config/SecurityConfig.java
- MyohanMeeting/src/main/java/meet/myo/config/WebConfig.java
> fix / OPTIONS 요청 허용
